name: mady_seller
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.1
  http: ^0.13.4
  shared_preferences: ^2.0.13

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sale-yellow.png
    - assets/images/sale-white.png
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/vazir.ttf
